### ISSUE TITLE
As a User, I want to create Boards to organize work

### ISSUE THREAD

**Issue by felipe-kosouski** [felipe-kosouski/scrumorganizer#18]
This issue is about creating the `Board` model, an it's respective controllers and views.

**Tasks**
- [x] Create Boards CRUD
- [x] Relate boards to projects *
- [x] Show all boards in card-like structure inside a project
- [x] Show flash messages when a Board is created, updated and deleted
- [x] Redirect to `Project` show action when a `Board` is created, updated or deleted
- [ ] Write tests

* Observations
- A project can have many boards.
