### ISSUE TITLE
As a user, I want to manage my info

### ISSUE THREAD

**Issue by felipe-kosouski** [felipe-kosouski/scrumorganizer#2]
**Create User area**
The users will be separated in 3 different roles, `Product Manager`, `Scrum Master` and `Developer`. Each one of them will have different permissions. (The roles and user permissions will be implemented in the next sprints).
As for the basic user info, we'll be using:

- Name
- Username
- Email
- Password

**Tasks**
- [x] Create User views
- [x] Create User validations
- [ ] Write User tests
