### ISSUE TITLE
As a guest, I want to be able to sign up to use the software

### ISSUE THREAD

**Issue by felipe-kosouski** [felipe-kosouski/scrumorganizer#3]
**Sign up within the home page**
The guest user must be able to access a public home page, and from that page, access an area to sign up. After signed up, the user must be redirected to the dashboard.

**Tasks**
- [x] Create a public home page
- [x] Create a sign up form
- [x] Create User CRUD (actually only CREATE for now)
- [x] Create validations for `Username`, `Email` and `Password` (see rules for validations below)
- [x] Redirect user to dashboard showing a success message
- [x] Write tests

**Validation Rules**
- Username must accept only letters, numbers and special caracters like `.` and `-`
- Email must be of a valid format
- Passwords must have more than 6 digits, accepting letters, numbers and symbols
