### ISSUE TITLE
As a User, I want to create a project to organize boards

### ISSUE THREAD

**Issue by felipe-kosouski** [felipe-kosouski/scrumorganizer#4]
This issue is about creating the `Project` model and it's controllers and views.

**Tasks**
- [x] Create `Project` CRUD
- [x] Create a view to show all projects
- [x] Relate Projects to Users *
- [x] After a `Project` is created, the user must be redirected to that project view.
- [x] Write Tests

* Observations
- A user can create many projects, but a project can be created by only one user.
