### ISSUE TITLE
As a User, I want to create Issues/Stories for a board

### ISSUE THREAD

**Issue by felipe-kosouski** [felipe-kosouski/scrumorganizer#5]
This issue is about creating and defining models, controllers and views for `Issues`

**Tasks**
- [ ] Create `Issues/Stories`  CRUD
- [ ] Relate issues to boards *
- [ ] Relate Issues to users * 
- [ ] Show issues inside boards
- [ ] When created, the issue is automatically placed on Product Backlog Board
- [ ] Write Tests

* Observations
- One `Issue` belongs to only one board
- The creator of an issue must be a user
